version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./broker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  edge-simulator-node-1:
    build:
      context: ./edge-simulator/node-1
    depends_on:
      - mqtt-broker

  edge-simulator-node-2:
    build:
      context: ./edge-simulator/node-2
    depends_on:
      - mqtt-broker

  ingest-server:
    build:
      context: ./ingest-server
    depends_on:
      - mqtt-broker

  dashboard-server:
    build:
      context: ./dashboard/server
    depends_on:
      - ingest-server

  dashboard-client:
    build:
      context: ./dashboard/client
    depends_on:
      - dashboard-server

networks:
  default:
    driver: bridge