version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    volumes:
      - ./broker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
  
  edge-agent:
    build:
      context: ./edge-agent
    depends_on:
      - mqtt-broker

  cloud-ingest:
    build:
      context: ./cloud-ingest
    depends_on:
      - mqtt-broker

  dashboard:
    build:
      context: ./dashboard
    depends_on:
      - cloud-ingest
    ports:
      - "3000:3000"