#version: '3.8'

services:
  mosquitto:
    build:
      context: ./mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config

  edge-node:
    build:
      context: ../services/edge-node
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883

  gateway:
    build:
      context: ../services/gateway
    depends_on:
      - mosquitto

  collector:
    build:
      context: ../services/collector

volumes:
  mosquitto_data:
  mosquitto_config: